Repository Vishwas2/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#68 added Perfect_Squares.java
  MediumDifficulty/src/Perfect_Squares.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#71 Create Reverse_integer.java
  EasyDifficulty/src/Reverse_integer.java
Labels: good first issue, hacktoberfest-accepted

#80 Length Of Last Word
  EasyDifficulty/src/Length_Of_Last_Word.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#79 Sort_Color
  MediumDifficulty/src/sort_color.java
Labels: good first issue, hacktoberfest-accepted

#83 added Factorial Trailing Zeroes solution
  MediumDifficulty/src/Factorial_Trailing_Zeroes.java
Labels: good first issue, Hacktoberfest2023, hacktoberfest-accepted

#94 Fixed issue #87
  MediumDifficulty/src/Longest_Increasing_Subsequence.java
Labels: good first issue, Hacktoberfest2023, hacktoberfest-accepted

#96 Flood Fill Algorithm ( Graph ) #70
  EasyDifficulty/src/Flood_Fill.java
Labels: good first issue, Hacktoberfest2023, hacktoberfest-accepted

#97 Create Container_With_Most_Water.java
  EasyDifficulty/src/Container_With_Most_Water.java
Labels: good first issue, Hacktoberfest2023, hacktoberfest-accepted
